CREATE DATABASE SMZ01_2018;

USE SMZ01_2018;

CREATE TABLE TYPE_MIDIA(
TMIDIA_ID int NOT NULL auto_increment,
TMIDIA_NAME varchar(15) NOT NULL unique,
primary key (TMIDIA_ID)
);

CREATE TABLE MIDIA(
MIDIA_ID int NOT NULL auto_increment,
MIDIA_NAME varchar(40) NOT NULL,
MIDIA_DATE datetime NOT NULL,
MIDIA_URL varchar(150) NOT NULL,
TMIDIA_ID int,
primary key (MIDIA_ID),
foreign key (TMIDIA_ID) references TYPE_MIDIA(TMIDIA_ID)
);

CREATE TABLE SOCIAL(
SOCIAL_ID int NOT NULL auto_increment,
SOCIAL_NAME varchar(40) NOT NULL,
SOCIAL_LINK varchar(150) NULL,
SOCIAL_STATUS boolean NOT NULL,
MIDIA_ID int,
primary key (SOCIAL_ID),
foreign key (MIDIA_ID) references MIDIA(MIDIA_ID)
);

CREATE TABLE APPLICATION(
APPLICATION_ID int NOT NULL auto_increment,
APPLICATION_NAME varchar(70) NOT NULL unique,
primary key (APPLICATION_ID)
);

CREATE TABLE PRODUCT(
PRODUCT_ID int NOT NULL auto_increment,
PRODUCT_NAME varchar(20) NOT NULL,
PRODUCT_DESCRIPTION text(4000) NOT NULL,
PRODUCT_STATUS boolean NOT NULL,
MIDIA_ID int,
primary key (PRODUCT_ID),
foreign key (MIDIA_ID) references MIDIA(MIDIA_ID)
);

CREATE TABLE APPLICATION_PRODUCT(
APRODUCT_ID int NOT NULL auto_increment,
APRODUCT_STATUS varchar(20) NOT NULL,
PRODUCT_ID int,
APPLICATION_ID int,
primary key (APRODUCT_ID),
foreign key (PRODUCT_ID) references PRODUCT(PRODUCT_ID),
foreign key (APPLICATION_ID) references APPLICATION(APPLICATION_ID)
);

--Feito

CREATE TABLE CAT_CTRL_QUALITY(
CCQUALITY_ID int NOT NULL auto_increment,
CCQUALITY_NAME varchar(25) NOT NULL unique,
primary key (CCQUALITY_ID)
);

CREATE TABLE SUB_CAT_CTRL_QUALITY(
SCCQUALITY_ID INT NOT NULL auto_increment,
SCCQUALITY_NAME varchar(25) NOT NULL UNIQUE,
CCQUALITY_ID int,
primary key (SCCQUALITY_ID),
foreign key (CCQUALITY_ID) references CAT_CTRL_QUALITY(CCQUALITY_ID)
);

CREATE TABLE CTRL_QUALITY(
CQUALITY_ID int NOT NULL auto_increment,
CQUALITY_VALUE float(20),
CQUALITY_DATE date,
SCCQUALITY_ID int,
PRODUCT_ID int,
primary key (CQUALITY_ID),
foreign key (SCCQUALITY_ID) references SUB_CAT_CTRL_QUALITY(SCCQUALITY_ID),
foreign key (PRODUCT_ID) references PRODUCT(PRODUCT_ID)
);

CREATE TABLE END_FACTORY(
EFACTORY_ID int NOT NULL auto_increment,
EFACTORY_COUNTRY varchar(30) NOT NULL,
EFACTORY_STATE varchar(40) NOT NULL,
EFACTORY_CITY varchar(40) NOT NULL,
EFACTORY_BURGH varchar(45),
EFACTORY_STREET varchar(70) NOT NULL,
EFACTORY_NUM varchar(15),
EFACTORY_ZIPCODE varchar(15) NOT NULL,
EFACTORY_LONGITUDE varchar(50),
EFACTORY_LATITUDE varchar(50),
primary key (EFACTORY_ID)
);

CREATE TABLE FAC_CONTACT(
FCONTACT_ID int NOT NULL auto_increment,
FCONTACT_NAME varchar(35) NOT NULL,
FCONTACT_MAIL varchar(150) NOT NULL,
FCONTACT_TEL varchar(35) NOT NULL,
FCONTACT_CEL varchar(35),
FCONTACT_HOURS varchar(30),
FCONTACT_STATUS boolean,
MIDIA_ID int,
EFACTORY_ID int,
primary key (FCONTACT_ID),
foreign key (MIDIA_ID) references MIDIA(MIDIA_ID),
foreign key (EFACTORY_ID) references END_FACTORY(EFACTORY_ID)
);

--Feito

CREATE TABLE COMPANY(
COMPANY_ID int NOT NULL auto_increment,
COMPANY_NAME varchar(45),
COMPANY_DESCRIPTION TEXT(4000),
MIDIA_ID int,
FCONTACT_ID int,
primary key (COMPANY_ID),
foreign key (MIDIA_ID) references MIDIA(MIDIA_ID),
foreign key (FCONTACT_ID) references FAC_CONTACT(FCONTACT_ID)
);

CREATE TABLE MENU (
  MENU_ID INT NOT NULL AUTO_INCREMENT,
  MENU_NAME VARCHAR(25) NOT NULL UNIQUE,
  MENU_STATUS BOOLEAN NOT NULL,
  PRIMARY KEY (MENU_ID)
);

CREATE TABLE SUB_MENU(
  SMENU_ID INT NOT NULL AUTO_INCREMENT,
  SMENU_NAME VARCHAR(30) NOT NULL,
  SMENU_STATUS BOOLEAN NOT NULL,
  MENU_ID INT,
  PRIMARY KEY (SMENU_ID),
  FOREIGN KEY (MENU_ID) REFERENCES MENU(MENU_ID)
);

--Feito!

CREATE TABLE ACCESSP(
  ACCESS_ID INT NOT NULL AUTO_INCREMENT,
  ACCESS_NAME VARCHAR(20) NOT NULL,
  PRIMARY KEY (ACCESS_ID)
);

/*
CREATE TABLE USERP(
  USER_ID INT NOT NULL AUTO_INCREMENT,
  USER_FNAME VARCHAR(15),
  USER_LNAME VARCHAR(55),
  USER_DEPARTAMENT VARCHAR(20),
  USER_MAIL VARCHAR(150) UNIQUE,
  USER_PASSWORD VARCHAR(60),
  COMPANY_ID INT,
  ACCESS_ID INT,
  PRIMARY KEY (USER_ID),
  FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(COMPANY_ID),
  FOREIGN KEY (ACCESS_ID)  REFERENCES ACCESSP(ACCESS_ID)
);

*/


CREATE TABLE CONTENT( --NOME ALTERADO PARA MIOLO = CORE'
  CONTENT_ID INT NOT NULL AUTO_INCREMENT,
  CONTENT_TILE VARCHAR(50) NOT NULL,
  CONTENT_DESCRIPTION TEXT(4000) NOT NULL,
  MIDIA_ID INT,
  MENU_ID INT,
  USER_ID INT,
  PRIMARY KEY (CONTENT_ID),
  FOREIGN KEY (MIDIA_ID) REFERENCES MIDIA(MIDIA_ID),
  FOREIGN KEY (MENU_ID)  REFERENCES MENU(MENU_ID),
  FOREIGN KEY (USER_ID)  REFERENCES USERP(USER_ID)
);

CREATE TABLE SHIPPING_EMAIL(
  SEMAIL_ID INT NOT NULL AUTO_INCREMENT,
  SEMAIL_PORT INT NOT NULL,
  SEMAIL_HOST VARCHAR(30) NOT NULL,
  SEMAIL_ISHTML BOOLEAN NOT NULL,
  SEMAIL_MAILER VARCHAR(10) NOT NULL,
  SEMAIL_SMTP_SECURE VARCHAR(10) NOT NULL,
  SEMAIL_USER VARCHAR(150) NOT NULL,
  SEMAIL_PASS VARCHAR(60) NOT NULL,
  USER_ID INT,
  PRIMARY KEY (SEMAIL_ID),
  FOREIGN KEY (USER_ID) REFERENCES USERP(USER_ID)
);

CREATE TABLE BE_CLIENT(
  CLIENT_ID INT NOT NULL AUTO_INCREMENT,
  CLIENT_COMPANY_NAME VARCHAR(60) NOT NULL,
  CLIENT_CNPJ VARCHAR(18) NOT NULL,
  CLIENT_CONTACT_NAME VARCHAR(60) NOT NULL,
  CLIENT_MAIL VARCHAR(150) NOT NULL,
  CLIENT_STATE VARCHAR(40) NOT NULL,
  CLIENT_CITY VARCHAR(40) NOT NULL,
  CLIENT_TPHONE VARCHAR(35) NOT NULL,
  CLIENT_CPHONE VARCHAR(35),
  CLIENT_CAME_TO_US VARCHAR(20) NOT NULL,
  SEMAIL_ID INT,
  PRIMARY KEY (CLIENT_ID),
  FOREIGN KEY (SEMAIL_ID) REFERENCES SHIPPING_EMAIL(SEMAIL_ID)
);

-- feito

CREATE TABLE CONTACT_US(
  CONTACT_ID INT NOT NULL AUTO_INCREMENT,
  CONTACT_FNAME VARCHAR(15) NOT NULL,
  CONTACT_LNAME VARCHAR(55) NOT NULL,
  CONTACT_MAIL VARCHAR(150) NOT NULL,
  CONTACT_TPHONE VARCHAR(35) NOT NULL,
  CONTACT_CPHONE VARCHAR(35),
  CONTACT_CITY VARCHAR(40) NOT NULL,
  CONTACT_STATE VARCHAR(40) NOT NULL,
  CONTACT_MESSAGE TEXT(4000) NOT NULL,
  SEMAIL_ID INT,
  PRIMARY KEY (CONTACT_ID),
  FOREIGN KEY (SEMAIL_ID) REFERENCES SHIPPING_EMAIL(SEMAIL_ID)
);

CREATE TABLE JOB ( -- NOME ALTERADO PARA WORK
  JOB_ID INT NOT NULL AUTO_INCREMENT,
  JOB_TITLE VARCHAR(50) NOT NULL,
  JOB_DESCRIPTION TEXT(4000) NOT NULL,
  EFACTORY_ID INT,
  USER_ID INT,
  PRIMARY KEY (JOB_ID),
  FOREIGN KEY (EFACTORY_ID) REFERENCES END_FACTORY(EFACTORY_ID),
  FOREIGN KEY (USER_ID) REFERENCES USERP(USER_ID)
);

CREATE TABLE CANDIDATE_JOB (-- NOME ALTERADO PARA CANDIDATE_WORK
  CJOB_ID INT NOT NULL AUTO_INCREMENT,
  CJOB_FNAME VARCHAR(15) NOT NULL,
  CJOB_LNAME VARCHAR(55) NOT NULL,
  CJOB_CEP  VARCHAR(10) NOT NULL,
  CJOB_STATE VARCHAR(40) NOT NULL,
  CJOB_CITY VARCHAR(40) NOT NULL,
  CJOB_BURGH VARCHAR(45) NOT NULL,
  CJOB_STREET VARCHAR(70) NOT NULL,
  CJOB_NUM VARCHAR(15) NOT NULL,
  CJOB_COMPLEMENT VARCHAR(70) NOT NULL,
  CJOB_GENDER VARCHAR(25) NOT NULL,
  CJOB_MAIL VARCHAR(150) NOT NULL,
  CJOB_TPHONE VARCHAR(35) NOT NULL,
  CJOB_CPHONE VARCHAR(35) NOT NULL,
  JOB_ID INT,
  PRIMARY KEY (CJOB_ID),
  FOREIGN KEY (JOB_ID) REFERENCES JOB(JOB_ID)
);
